_target_: temporal_task_planner.trainer.module_wrapper.ModuleWrapper
method_name: 'Adam'
# params: model.parameters()
lr: ${lr}
betas: (0.9, 0.999)
# momentum: 0.9
# weight_decay: 0.000001
# dampening: 0.01