robot:
  _target_: polygrasp.robot_interface.GraspingRobotInterface
  ip_address: "100.67.224.116"
  enforce_version: false
  gripper:
    _target_: polymetis.GripperInterface

camera_sub:
  _target_: polygrasp.cam_pub_sub.PointCloudSubscriber
  intrinsics_file: conf/intrinsics.json
  extrinsics_file: ../eyehandcal/calibration.json

masks_1:
  - conf/masks/bin1/1.png
  - conf/masks/bin1/2.png
  - conf/masks/bin1/3.png
masks_2:
  - conf/masks/bin2/1.png
  - conf/masks/bin2/2.png
  - conf/masks/bin2/3.png

view_json_path: conf/o3d_view.json
min_mask_size: 2500