robot:
  _target_: polygrasp.robot_interface.GraspingRobotInterface
  ip_address: "100.67.224.116"
  enforce_version: false
  gripper:
    _target_: polymetis.GripperInterface

camera_extrinsics_path: ../eyehandcal/calibration.json
view_json_path: conf/o3d_view.json
