robot:
  _target_: polygrasp.robot_interface.GraspingRobotInterface
  ip_address: "100.67.224.116"
  enforce_version: false
  gripper:
    _target_: polymetis.GripperInterface

camera_sub:
  _target_: polygrasp.cam_pub_sub.CameraSubscriber
  intrinsics_file: conf/intrinsics.json
  extrinsics_file: ../eyehandcal/calibration.json

view_json_path: conf/o3d_view.json
