_target_: temporal_task_planner.trainer.module_wrapper.ModuleWrapper
method_name: 'DualModelLogger'
env: ${envs}
config: ${learner.config}
model: ${model}
criterion: ${criterion}
pick_only: ${pick_only}
max_evals: 10
savefolder: ${rollout_savefolder}