_target_: temporal_task_planner.trainer.module_wrapper.ModuleWrapper
method_name: 'SingleModelLogger'
config: ${learner.config}
model: ${model}
criterion: ${criterion}
pick_only: ${pick_only}
max_evals: ${max_evals}
savefolder: "rollouts"