robot:
  _target_: polygrasp.robot_interface.GraspingRobotInterface
  ip_address: "100.67.224.116"
  enforce_version: false
  k_approach: 0.9
  k_grasp: 0.55
  gripper:
    _target_: polymetis.GripperInterface
